services:
  db:
    image: mysql
    container_name: terceiraapi_db
    environment:
      MYSQL_ROOT_PASSWORD: root # Defina a senha do usuário root
      MYSQL_DATABASE: mydb         # Nome do banco de dados que será criado       # Senha do usuário
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql2

volumes:
  db_data:
