services:
  db:
    image: mysql:8.0
    container_name: segundaapi_db
    environment:
      MYSQL_ROOT_PASSWORD: sa # Defina a senha do usu치rio root
      MYSQL_DATABASE: testdb         # Nome do banco de dados que ser치 criado
      MYSQL_USER: sa                      # Nome do usu치rio
      MYSQL_PASSWORD: sa         # Senha do usu치rio
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql2

volumes:
  db_data:
